name: 'student_dbt'
version: '1.0.0'
config-version: 2

profile: 'student_dbt'

# dbt-mysql adapter plugin
dispatch:
  - macro_namespace: dbt
    search_order: ['dbt_mysql', 'dbt']

model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  student_dbt:
    staging:
      +materialized: view
      +schema: student_dwh
    marts:
      +materialized: table
      +schema: student_data_mart
